"""

Problem 2: Even Fibonacci numbers
---------------------------------

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def solve(n):
    a, b = 0, 1
    sum = 0
    while a+b<=n:
        a, b = b, a+b
        if b%2==0:
            sum += b
    return sum


def compute():
    n = 4000000
    return solve(n)
    